version: '3.9'

services:
  app:
    container_name: app
    image: marcelofabianov/php8.3-fpm:latest
    build:
      context: ./_docker/local/php-fpm
      dockerfile: Dockerfile
    restart: always
    command: php -S 0.0.0.0:8888 -t /var/www
    volumes:
      - ./dev/:/var/www
    ports:
      - "9000:9000"
      - "9003:9003"
      - "8888:8888"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
